packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': false
  argon2: false
  esbuild: false
  prisma: false
  protobufjs: true
  unrs-resolver: false
