syntax = "proto3";

package auth;

service AuthService {
  rpc Signup (SignupRequest) returns (SignupResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc GetSessionEmail (GetSessionEmailRequest) returns (GetSessionEmailResponse);
}

message SignupRequest {
  string email = 1;
  string password = 2;
}

message SignupResponse {
  bool success = 1;
  string message = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string message = 2;
  string sessionToken = 3;
}

message GetSessionEmailRequest {
  string sessionToken = 1;
}

message GetSessionEmailResponse {
  string email = 1;
}
